# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [7]:
# 記得先 Import 正確的套件

import numpy as np

In [16]:
a = np.arange(12)
b = []

for i in a:
    if i < 3:
        b.append(i)
    elif i > 6:
        b.append(i)
    else:
        b.append(-i)
print(b)

[0, 1, 2, -3, -4, -5, -6, 7, 8, 9, 10, 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [29]:
A = np.random.rand(3, 6)
print(A)
print("比0.5大的元素共有",A[A>0.5].size,"個")

[[0.08125173 0.90511815 0.89023267 0.9930885  0.61213642 0.90094002]
 [0.01381225 0.77204186 0.39145351 0.68230494 0.25772598 0.79271498]
 [0.2076943  0.87152549 0.88184988 0.08642747 0.40049367 0.68266918]]
比0.5大的元素共有 11 個
